"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from scrapy.spiders import Spider
from typing_extensions import Self
from scrapy.crawler import Crawler

if TYPE_CHECKING:
    ...
logger = ...
class SitemapSpider(Spider):
    sitemap_urls = ...
    sitemap_rules = ...
    sitemap_follow = ...
    sitemap_alternate_links = ...
    _max_size: int
    _warn_size: int
    @classmethod
    def from_crawler(cls, crawler: Crawler, *args: Any, **kwargs: Any) -> Self:
        ...
    
    def __init__(self, *a, **kw) -> None:
        ...
    
    def start_requests(self): # -> Generator[Request, Any, None]:
        ...
    
    def sitemap_filter(self, entries): # -> Generator[Any, Any, None]:
        """This method can be used to filter sitemap entries by their
        attributes, for example, you can filter locs with lastmod greater
        than a given date (see docs).
        """
        ...
    


def regex(x): # -> Pattern[str]:
    ...

def iterloc(it, alt=...): # -> Generator[Any, Any, None]:
    ...

